/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/
import type { DeviceProps } from '../../../types';
import { getFileUri } from '../../../utils';


export const STATUS_BAR_TYPE = {
    NORMAL: 'normal',
    NOTCH: 'notch',
    DYNAMIC_ISLAND: 'dynamicIsland',
};


const devices: DeviceProps[] = [
    {
        value: 'iPhoneX',
        label: 'iPhoneX',
        screenWidth: 375,
        screenHeight: 812,
        winWidth: 430,
        winHeight: 860,
        padding: [24, 28, 0, 28],
        statusHeight: 40,
        borderRadius: '40px',
        frame: getFileUri('vs/workbench/browser/parts/simulator/resources/iphone-x.png'),
        statusBarType: STATUS_BAR_TYPE.NOTCH,
    },
    {
        value: 'iPhone5',
        label: 'iPhone5',
        screenWidth: 320,
        screenHeight: 568,
        winWidth: 380,
        winHeight: 794,
        padding: [117, 29, 0, 32],
        statusHeight: 20,
        borderRadius: '0px',
        frame: getFileUri('vs/workbench/browser/parts/simulator/resources/iphone-5.png'),
        statusBarType: STATUS_BAR_TYPE.NORMAL,
    },
    {
        value: 'iPhone6/7/8',
        label: 'iPhone6/7/8',
        screenWidth: 375,
        screenHeight: 667,
        winWidth: 436,
        winHeight: 889,
        padding: [110, 30, 0, 30],
        statusHeight: 20,
        borderRadius: '0px',
        frame: getFileUri('vs/workbench/browser/parts/simulator/resources/iphone-se.png'),
        statusBarType: STATUS_BAR_TYPE.NORMAL,
    },

    {
        value: 'iPhone 6/7/8 Plus ',
        label: 'iPhone 6/7/8 Plus ',
        screenWidth: 414,
        screenHeight: 974,
        winWidth: 483,
        winHeight: 897,
        padding: [124, 34, 0, 34],
        statusHeight: 20,
        borderRadius: '0px',
        frame: getFileUri('vs/workbench/browser/parts/simulator/resources/iphone-se.png'),
        statusBarType: STATUS_BAR_TYPE.NORMAL,
    },
    {
        value: 'iPhone XS Max ',
        label: 'iPhone XS Max ',
        screenWidth: 414,
        screenHeight: 896,
        winWidth: 414,
        winHeight: 896,
        padding: [24, 28, 0, 28],
        statusHeight: 44,
        borderRadius: '39px',
        frame: getFileUri('vs/workbench/browser/parts/simulator/resources/iphone-x.png'),
        statusBarType: STATUS_BAR_TYPE.NOTCH,
    },
    {
        value: 'iPhone 12/13 mini ',
        label: 'iPhone 12/13 mini ',
        screenWidth: 360,
        screenHeight: 780,
        winWidth: 407,
        winHeight: 821,
        padding: [20, 24, 0, 24],
        statusHeight: 44,
        borderRadius: '44px',
        frame: getFileUri('vs/workbench/browser/parts/simulator/resources/iphone-12mini.png'),
        statusBarType: STATUS_BAR_TYPE.NOTCH,
    },
    {
        value: 'iPhone 12/13(Pro)',
        label: 'iPhone 12/13(Pro)',
        screenWidth: 390,
        screenHeight: 844,
        winWidth: 438,
        winHeight: 887,
        padding: [20, 24, 0, 24],
        statusHeight: 44,
        borderRadius: '48px',
        frame: getFileUri('vs/workbench/browser/parts/simulator/resources/iphone-13pro.png'),
        statusBarType: STATUS_BAR_TYPE.NOTCH,
    },
    {
        value: 'iPhone 12/13 Pro Max ',
        label: 'iPhone 12/13 Pro Max ',
        screenWidth: 428,
        screenHeight: 926,
        winWidth: 476,
        winHeight: 965,
        padding: [20, 24, 0, 24],
        statusHeight: 44,
        borderRadius: '53px',
        frame: getFileUri('vs/workbench/browser/parts/simulator/resources/iphone-13promax.png'),
        statusBarType: STATUS_BAR_TYPE.NOTCH,
    },
    {
        value: 'iPhone 14 Pro',
        label: 'iPhone 14 Pro',
        screenWidth: 390,
        screenHeight: 842,
        winWidth: 435,
        winHeight: 883,
        padding: [19, 22, 0, 22],
        statusHeight: 55,
        borderRadius: '58px',
        frame: getFileUri('vs/workbench/browser/parts/simulator/resources/iphone-14pro.png'),
        statusBarType: STATUS_BAR_TYPE.DYNAMIC_ISLAND,
    },
    {
        value: 'iPhone 14 Pro Max ',
        label: 'iPhone 14 Pro Max ',
        screenWidth: 428,
        screenHeight: 926,
        winWidth: 428,
        winHeight: 926,
        padding: [19, 22, 0, 22],
        statusHeight: 50,
        borderRadius: '53px',
        frame: getFileUri('vs/workbench/browser/parts/simulator/resources/iphone-14pro.png'),
        statusBarType: STATUS_BAR_TYPE.DYNAMIC_ISLAND,
    },
];

export default devices;
