<template>
	<n-select v-model:value="value" size="tiny" :options="options" :consistent-menu-width="false"/>
</template>

<script setup lang="ts">
import { NSelect } from "naive-ui";
import { ref } from "vue";

const statusbarType = {
	NORMAL: "normal",
	NOTCH: "notch",
	DYNAMIC_ISLAND: "dynamic-island",
};

const PLATFORMS = {
	MOBILE: "mobile",
};

const value = ref("");
value.value = "iPhone5";
const options = [
  {
		value: "iPhone5",
		label: "iPhone5",
		width: 320,
		height: 568,
		win_width: 380,
		win_height: 794,
		padding: "117px 29px 0px 32px",
		statusHei: 20,
		statusbarType: statusbarType.NORMAL,
		frame: "",
		Dpr: 2,
		platform: PLATFORMS.MOBILE,
	},
	{
		value: "iPhone6/7/8",
		label: "iPhone6/7/8",
		width: 375,
		height: 667,
		win_width: 436,
		win_height: 889,
		padding: "110px 30px 0px 30px",
		statusHei: 20,
		statusbarType: statusbarType.NORMAL,
		frame: "",
		Dpr: 2,
		radius: "0px",
		platform: PLATFORMS.MOBILE,
	},
	{
		value: "iPhone 6/7/8 Plus ",
		label: "iPhone 6/7/8 Plus ",
		width: 414,
		height: 736,
		win_width: 483,
		win_height: 897,
		padding: "124px 34px 0px 34px",
		statusHei: 20,
		statusbarType: statusbarType.NORMAL,
		frame: "",
		Dpr: 3,
		radius: "0px",
		platform: PLATFORMS.MOBILE,
	},
	{
		value: "iPhone X ",
		label: "iPhone X ",
		width: 375,
		height: 812,
		win_width: 431,
		win_height: 863,
		padding: "24px 28px 0px 28px",
		statusHei: 44,
		statusbarType: statusbarType.NOTCH,
		frame: "",
		Dpr: 3,
		radius: "39px",
		platform: PLATFORMS.MOBILE,
	},
	{
		value: "iPhone XS Max ",
		label: "iPhone XS Max ",
		width: 414,
		height: 896,
		win_width: 414,
		win_height: 896,
		statusHei: 44,
		Dpr: 3,
		statusbarType: statusbarType.NOTCH,
		radius: "39px",
		platform: PLATFORMS.MOBILE,
	},
	{
		value: "iPhone 12/13 mini ",
		label: "iPhone 12/13 mini ",
		width: 360,
		height: 780,
		win_width: 407,
		win_height: 821,
		padding: "20px 24px 0px 24px",
		statusHei: 44,
		statusbarType: statusbarType.NOTCH,
		frame: "",
		Dpr: 3,
		radius: "44px",
		platform: PLATFORMS.MOBILE,
	},
	{
		value: "iPhone 12/13(Pro)",
		label: "iPhone 12/13(Pro)",
		width: 390,
		height: 844,
		win_width: 438,
		win_height: 887,
		padding: "20px 24px 0px 24px",
		statusHei: 44,
		statusbarType: statusbarType.NOTCH,
		frame: "",
		Dpr: 3,
		radius: "48px",
		platform: PLATFORMS.MOBILE,
	},
	{
		value: "iPhone 12/13 Pro Max ",
		label: "iPhone 12/13 Pro Max ",
		width: 428,
		height: 926,
		win_width: 476,
		win_height: 965,
		padding: "20px 24px 0px 24px",
		statusHei: 44,
		statusbarType: statusbarType.NOTCH,
		frame: "",
		Dpr: 3,
		radius: "53px",
		platform: PLATFORMS.MOBILE,
	},
	{
		value: "iPhone 14 Pro",
		label: "iPhone 14 Pro",
		width: 390,
		height: 842,
		win_width: 435,
		win_height: 883,
		padding: "19px 22px 0px 22px",
		statusHei: 55,
		statusbarType: statusbarType.DYNAMIC_ISLAND,
		frame: "",
		Dpr: 3,
		radius: "58px",
		platform: PLATFORMS.MOBILE,
	},
	{
		value: "iPhone 14 Pro Max ",
		label: "iPhone 14 Pro Max ",
		width: 428,
		height: 926,
		win_width: 428,
		win_height: 926,
		statusHei: 50,
		statusbarType: statusbarType.DYNAMIC_ISLAND,
		Dpr: 3,
		radius: "53px",
		platform: PLATFORMS.MOBILE,
	},
];
</script>
